import { GoogleGenAI } from "@google/genai";
import { OccasionTheme, OutfitResult } from "../types";

const IMAGE_MODEL = "gemini-2.5-flash-image";
const VISION_MODEL = "gemini-2.5-flash";

export const generateAndDescribeOutfit = async (
  userImageBase64: string,
  clothingImageBase64: string,
  theme: OccasionTheme,
  userMimeType: string,
  clothingMimeType: string
): Promise<OutfitResult> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  // Step 1: Generate the outfit image
  const imageGenerationPrompt = `On the basis of the attached photo of a person and a clothing item, and the selected vibe "${theme}", please create a single image of a perfect outfit that looks and feels like GEN-Z. The clothing should be classy, color-complementing, and the user should feel confident looking at it. Generate only the image.`;

  const imageResponse = await ai.models.generateContent({
    model: IMAGE_MODEL,
    contents: {
      parts: [
        { text: imageGenerationPrompt },
        {
          inlineData: {
            mimeType: userMimeType,
            data: userImageBase64,
          },
        },
        {
          inlineData: {
            mimeType: clothingMimeType,
            data: clothingImageBase64,
          },
        },
      ],
    },
  });
  
  let generatedImageBase64: string | null = null;
  for (const part of imageResponse.candidates[0].content.parts) {
    if (part.inlineData) {
      generatedImageBase64 = part.inlineData.data;
      break;
    }
  }

  if (!generatedImageBase64) {
    throw new Error("No image was generated by the model.");
  }

  // Step 2: Describe the generated image for a search query
  const descriptionPrompt = "Analyze the provided image and describe the complete outfit in a short, concise phrase suitable for a Google Shopping search query. Focus on the main clothing items, colors, and styles. Example: 'oversized graphic t-shirt, light wash baggy jeans, platform sneakers'.";

  const descriptionResponse = await ai.models.generateContent({
    model: VISION_MODEL,
    contents: {
      parts: [
        { text: descriptionPrompt },
        {
          inlineData: {
            mimeType: 'image/png', // The generated image will be a PNG
            data: generatedImageBase64,
          },
        },
      ],
    },
  });

  const description = descriptionResponse.text;
  if (!description) {
    throw new Error("Could not generate a description for the image.");
  }

  return {
    imageBase64: generatedImageBase64,
    description: description.trim(),
  };
};
